joke_register:
    path:     /register
    defaults: { _controller: AcmeJokeBundle:Register:index }

joke_register_save:
    path:     /register/save
    defaults: { _controller: AcmeJokeBundle:Register:save }

joke_login:
    path:     /login
    defaults: { _controller: AcmeJokeBundle:Login:index }

joke_login_check:
    path:     /login/check
    defaults: { _controller: AcmeJokeBundle:Login:check }

joke_list:
    path:     /list/{page}
    defaults: { _controller: AcmeJokeBundle:List:list }

