<?php

namespace Acme\JokeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * jokes_listRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class jokes_listRepository extends EntityRepository
{
}
